## Chargement des fonctions externes
library ("EBImage")
source ("rdfMoments.R")

calcul <- function(path){
    img <- rdfReadGreyImage(path)
    e <- eigen(rdfMomentCentreNormaliseOrdre2(img))
    e$values
}


carre6 <-calcul("img/rdf-carre-6.png")
carre10 <- calcul("img/rdf-carre-10.png")
carre30deg <- calcul("img/rdf-carre-10-30deg.png")
carre45deg <- calcul("img/rdf-carre-10-45deg.png")
carre20 <- calcul("img/rdf-carre-20.png")
rectH <- calcul("img/rdf-rectangle-horizontal.png")
rectV <- calcul("img/rdf-rectangle-vertical.png")
rectN <- calcul("img/rdf-rectangle-diagonal.png")
rectF <- calcul("img/rdf-rectangle-diagonal-lisse.png")
triangle10 <-calcul("img/rdf-triangle-10.png")
triangle15deg <-calcul("img/rdf-triangle-10-15deg.png")
triangle45deg <-calcul("img/rdf-triangle-10-45deg.png")
triangle60deg <-calcul("img/rdf-triangle-10-60deg.png")

cat("INVARIANCE AU CHANGEMENT DE FORME =======\n")
cat("Carré coté 6 : ", carre6, "\n")
cat("Carré côté 10 : ", carre10, "\n")
cat("différence avec carré 6 en % : ", cmpMatrice(carre6, carre10), "\n")
cat("Carré côté 20 : ", carre20, "\n")
cat("différence avec carré 6 en % : ", cmpMatrice(carre6, carre20), "\n")

cat("INVARIANCE À LA ROTATION (CARRE) =======\n")
cat("Carré côté 10 : ", carre10, "\n")
cat("Rotation 30deg : ", carre30deg, "\n")
cat("différence avec carré 10 en % : ", cmpMatrice(carre10, carre30deg), "\n")
cat("Rotation 45deg : ", carre45deg, "\n")
cat("différence avec carré 10 en % : ", cmpMatrice(carre10, carre45deg), "\n")
cat("INVARIANCE À LA ROTATION (RECTANGE) =======\n")
cat("rectangle horizontal : ", rectH, "\n")
cat("Rectangle vertical : ", rectV, "\n")
cat("différence avec rectangle horizontal en % : ", cmpMatrice(rectH, rectV), "\n")
cat("Rectangle diag : ", rectN, "\n")
cat("différence avec rectangle horizontal en % : ", cmpMatrice(rectH, rectN), "\n")
cat("Rectangle diagonal lisse : ", rectF, "\n")
cat("différence avec rectangle horizontal en % : ", cmpMatrice(rectH, rectF), "\n")

cat("INVARIANCE À LA ROTATION (TRIANGLE) =======\n")
cat("triangle coté 10 : ", triangle10, "\n")
cat("triangle 15deg : ", triangle15deg, "\n")
cat("différence avec triangle de coté 10 en % : ", cmpMatrice(triangle10, triangle15deg), "\n")
cat("triangle 45deg : ", triangle45deg, "\n")
cat("différence avec triangle de coté 10 en % : ", cmpMatrice(triangle10, triangle45deg), "\n")
cat("triangle 60deg : ", triangle60deg, "\n")
cat("différence avec triangle de coté 10 en % : ", cmpMatrice(triangle10, triangle60deg), "\n")
